name: Go
on: [push]
jobs:

  setup-artifacts:
    name: SetupArtifacts
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo '' > coverage.txt
      - name: Share Coverage Store
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage.txt

  test-platforms:
    name: ${{ matrix.platform }}-Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    needs: setup-artifacts
    steps:
    - name: Get Coverage Store
      uses: actions/download-artifact@v1
      with:
        name: coverage

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        mkdir -p /home/runner/go/bin
        go get -v -t -d ./...

    - name: Test
      run: go run coverage/cover.go ${{job.runs-on}}
    
    - name: Share Coverage Store
      uses: actions/upload-artifact@v1
      with:
          name: coverage
          path: coverage.txt
  push-coverage:
    name: Send Artifacts
    runs-on: ubuntu-latest
    needs: test-platforms
    steps:
    - name: Push to codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/coverage.txt
